version: '3.4'

services:
  vulnerable:
    image: ${DOCKER_REGISTRY-}vulnerable
    build:
      context: .
      dockerfile: Vulnerable/Dockerfile

  improved:
    image: ${DOCKER_REGISTRY-}improved
    build:
      context: .
      dockerfile: Improved/Dockerfile
